[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"
authors = ["fdb-rs Developers"]
license = "MIT OR Apache-2.0"

[features]
default = ["fdb/fdb-6_3"]

[dependencies]
fdb = "0.2"
tokio = { version = "1", features = ["full"] }

